name: frontend-deploy-dispatch

on:
  workflow_dispatch:
    inputs:
      ocptoken:
        required: true
      environment:
        required: true
        default: sit1
      projectName:
        required: true
        default: cmomobile-sit01
      selectpackage:
        required: true
        default: ALL
      selectall:
        required: true
        default: ALL

jobs:
  call:
    uses: ./.github/workflows/frontend-deploy.yml
    with:
      ocptoken: ${{ inputs.ocptoken }}
      environment: ${{ inputs.environment }}
      projectName: ${{ inputs.projectName }}
      selectpackage: ${{ inputs.selectpackage }}
      selectall: ${{ inputs.selectall }}
