name: Frontend Build

on:
  workflow_dispatch:
    inputs:
      version:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build frontend
        run: |
          echo "Building frontend version ${{ github.event.inputs.version }}"
