name: CMO Frontend Build (Dispatch)

on:
  workflow_dispatch:
    inputs:
      relordev:
        required: true
        default: Development
      relno:
        required: true
        default: "26.43"
      branchName:
        required: true
        default: develop
      buildimage:
        required: true
        default: Y
      uploadimage:
        required: true
        default: Y
      environment:
        required: true
        default: sit1

jobs:
  call:
    uses: ./.github/workflows/frontend-build.yml
    with:
      relordev: ${{ inputs.relordev }}
      relno: ${{ inputs.relno }}
      branchName: ${{ inputs.branchName }}
      buildimage: ${{ inputs.buildimage }}
      uploadimage: ${{ inputs.uploadimage }}
      environment: ${{ inputs.environment }}
