name: Frontend Deploy Pipeline

on:
  workflow_call:
    inputs:
      ocptoken: { type: string, required: true }
      environment: { type: string, required: true }
      projectName: { type: string, required: true }
      selectpackage: { type: string, required: true }
      selectall: { type: string, required: true }

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "=== DEPLOY INPUT ==="
          echo "${{ inputs.ocptoken }}"
          echo "${{ inputs.environment }}"

  deploy:
    needs: validate
    runs-on: ubuntu-latest
    steps:
      - run: echo "Deploying frontend..."

  restart:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - run: echo "Restart services"
