name: CMO Mobile Frontend - Deploy

on:
  workflow_dispatch:
    inputs:
      ocptoken:
        description: 'OCP Token'
        required: true

      environment:
        description: 'Environment'
        required: true
        default: sit1

      projectName:
        description: 'Project Name'
        required: true
        default: cmomobile-sit01

      selectpackage:
        description: 'Select Package'
        required: true
        default: ALL

      selectall:
        description: 'Type ALL'
        required: true
        default: ALL

jobs:
  call:
    uses: ./.github/workflows/frontend-deploy.yml
    with:
      ocptoken: ${{ inputs.ocptoken }}
      environment: ${{ inputs.environment }}
      projectName: ${{ inputs.projectName }}
      selectpackage: ${{ inputs.selectpackage }}
      selectall: ${{ inputs.selectall }}
